CREATE TABLE `commissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lead_id` int NOT NULL,
	`provider_id` int NOT NULL,
	`service_id` int NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`payment_method` varchar(50),
	`payment_intent_id` varchar(255),
	`commission_status` enum('pending','processing','paid','failed','refunded') NOT NULL DEFAULT 'pending',
	`invoice_url` varchar(500),
	`quote_url` varchar(500),
	`admin_validated` boolean NOT NULL DEFAULT false,
	`admin_validated_at` timestamp,
	`admin_validated_by` int,
	`admin_notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`paid_at` timestamp,
	CONSTRAINT `commissions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lead_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lead_id` int NOT NULL,
	`from_status` varchar(50),
	`to_status` varchar(50) NOT NULL,
	`changed_by` int,
	`reason` text,
	`metadata` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `lead_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lead_reservations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lead_id` int NOT NULL,
	`provider_id` int NOT NULL,
	`reserved_at` timestamp NOT NULL DEFAULT (now()),
	`expires_at` timestamp NOT NULL,
	`is_active` boolean NOT NULL DEFAULT true,
	`cancelled_at` timestamp,
	`cancel_reason` text,
	`converted` boolean NOT NULL DEFAULT false,
	`converted_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `lead_reservations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`service_id` int NOT NULL,
	`client_first_name` varchar(255) NOT NULL,
	`client_last_name` varchar(255) NOT NULL,
	`client_email` varchar(320) NOT NULL,
	`client_phone` varchar(20) NOT NULL,
	`client_address` text,
	`client_city` varchar(255),
	`client_postal_code` varchar(10),
	`service_data` json NOT NULL,
	`estimated_amount` decimal(10,2),
	`commission_amount` decimal(10,2) NOT NULL,
	`status` enum('pending','available','reserved','contacted','quote_sent','accepted','paid','completed','cancelled') NOT NULL DEFAULT 'pending',
	`reserved_by` int,
	`reserved_at` timestamp,
	`reserved_until` timestamp,
	`converted_by` int,
	`converted_at` timestamp,
	`accepted_terms` boolean NOT NULL DEFAULT true,
	`accepted_contact` boolean NOT NULL DEFAULT true,
	`source_url` varchar(500),
	`source_module` varchar(100),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `providers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`company_name` varchar(255) NOT NULL,
	`siret` varchar(14),
	`contact_name` varchar(255) NOT NULL,
	`contact_email` varchar(320) NOT NULL,
	`contact_phone` varchar(20) NOT NULL,
	`address` text,
	`city` varchar(255),
	`postal_code` varchar(10),
	`service_ids` json NOT NULL,
	`intervention_departments` json,
	`intervention_radius` int DEFAULT 50,
	`certifications` json,
	`provider_status` enum('pending','active','suspended','rejected') NOT NULL DEFAULT 'pending',
	`leads_received` int NOT NULL DEFAULT 0,
	`leads_converted` int NOT NULL DEFAULT 0,
	`total_spent` decimal(10,2) NOT NULL DEFAULT '0.00',
	`rating` decimal(3,2) DEFAULT '0.00',
	`review_count` int NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`validated_at` timestamp,
	`validated_by` int,
	CONSTRAINT `providers_id` PRIMARY KEY(`id`),
	CONSTRAINT `providers_user_id_unique` UNIQUE(`user_id`)
);
--> statement-breakpoint
CREATE TABLE `services` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(100) NOT NULL,
	`name` varchar(255) NOT NULL,
	`category` varchar(100) NOT NULL,
	`description` text,
	`icon` varchar(50),
	`commission_type` enum('fixed','percentage') NOT NULL DEFAULT 'percentage',
	`commission_value` decimal(10,2) NOT NULL,
	`commission_min` decimal(10,2),
	`commission_max` decimal(10,2),
	`requires_quote` boolean NOT NULL DEFAULT true,
	`reservation_duration` int NOT NULL DEFAULT 48,
	`custom_fields` json,
	`is_active` boolean NOT NULL DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `services_id` PRIMARY KEY(`id`),
	CONSTRAINT `services_slug_unique` UNIQUE(`slug`)
);
